import { CardSchema } from "../components/CardCourse/Card";

export const data: CardSchema[] = [
  {
    id: "123",
    courseTitle: "blockChain",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/bc-ar.png",
  },
  {
    id: "121",
    courseTitle: "Software Testing",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/swt-ar.png",
  },
  {
    id: "321",
    courseTitle: "Freelancing",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/freelancing-ar.png",
  },
  {
    id: "333",
    courseTitle: "E-Learning",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/elearning-ar.png",
  },
  {
    id: "322",
    courseTitle: "Machine Learning ( Deep Learning )",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/ai-en.png",
  },
  {
    id: "5645",
    courseTitle: "analog ic design",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/ic-ar.png",
  },
  {
    id: "56325",
    courseTitle: "Java Mobile Development",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/mobile-ar.png",
  },
  {
    id: "32432",
    courseTitle: "Internet of things",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/iot-ar.png",
  },
  {
    id: "323432",
    courseTitle: "Cyber Security",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/cyber-ar.png",
  },
  {
    id: "22442",
    courseTitle: "Front end Development ",
    price: 20,
    discount: 20,
    courseCount: 3,
    imgUrl: "/images/courses/frontend-ar.png",
  },
];
export const MainCardInit = {
  id: "234",
  imgUrl: "/images/topic/BlockChain developer.png",
  title: "softWare",
  studentsNumber: 200,
  UpdatedDate: "Updated 8/07/21",
  price: 2000,
  discount: 0,
};
